/**
 * Export helpers for post-mortem: Markdown download, PDF print, clipboard copy.
 */

function toMarkdown(pm) {
  return [
    `# Post-Mortem — ${pm.title}`,
    `**Date:** ${pm.date}`,
    `**Severity:** ${pm.severity}`,
    '',
    '## Summary',
    pm.summary,
    '',
    '## Timeline',
    (pm.timeline ?? []).map(t => `- **${t.time}** — ${t.event}`).join('\n'),
    '',
    '## Root Cause',
    pm.rootCause,
    '',
    '## Resolution',
    pm.resolution,
    '',
    '## Action Items',
    (pm.actionItems ?? []).map(a => `- [ ] ${a}`).join('\n'),
    '',
    '## Affected Services',
    (pm.affectedServices ?? []).join(', '),
    '',
    '---',
    '_Auto-generated by ClauseTrace AI_',
  ].join('\n')
}

export function downloadMarkdown(pm) {
  const blob = new Blob([toMarkdown(pm)], { type: 'text/markdown' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `postmortem-${pm.incidentId}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadPDF() {
  window.print()
}

export async function copyToClipboard(pm) {
  await navigator.clipboard.writeText(toMarkdown(pm))
}
